export const dataArray = [
  {
    id: 0,
    name: 'Guilt',
    author: 'Nero',
    album: 'Welcome Reality',
    duration_in_seconds: '4:44',
    release_date: 2023,
    genre: 'Хип-хоп',
  },
  {
    id: 1,
    name: 'Elektro',
    author: 'Dynoro, Outwork, Mr. Gee',
    album: 'Elektro',
    duration_in_seconds: '2:22',
    release_date: 2022,
    genre: 'Поп-музыка',
  },
  {
    id: 2,
    name: 'I’m Fire',
    author: 'Ali Bakgor',
    album: 'I’m Fire',
    duration_in_seconds: '2:22',
    release_date: 2021,
    genre: 'Техно',
  },
  {
    id: 3,
    name: 'Non Stop',
    author: 'Стоункат, Psychopath',
    album: 'Non Stop',
    duration_in_seconds: '4:12',
    release_date: 2020,
    genre: 'Инди',
  },
  {
    id: 4,
    name: 'Run Run',
    author: 'Jaded, Will Clarke, AR/CO',
    album: 'Run Run',
    duration_in_seconds: '2:54',
    release_date: 2019,
    genre: 'Рок',
  },
  {
    id: 5,
    name: 'Eyes on Fire',
    author: 'Blue Foundation, Zeds Dead',
    album: 'Eyes on Fire',
    duration_in_seconds: '5:20',
    release_date: 2023,
    genre: 'Из кино',
  },
  {
    id: 6,
    name: 'Mucho Bien',
    author: 'HYBIT, Mr. Black, Offer Nissim, Hi Profile',
    album: 'Mucho Bien',
    duration_in_seconds: '3:41',
    release_date: 2022,
    genre: 'Нью-эйдж',
  },
  {
    id: 7,
    name: 'Knives n Cherries',
    author: 'minthaze',
    album: 'Captivating',
    duration_in_seconds: '1:48',
    release_date: 2021,
    genre: 'Классика',
  },
  {
    id: 8,
    name: 'Knives n Cherries',
    author: 'minthaze',
    album: 'Captivating',
    duration_in_seconds: '1:48',
    release_date: 2020,
    genre: 'Поп-музыка',
  },
  {
    id: 9,
    name: 'Knives n Cherries',
    author: 'minthaze',
    album: 'Captivating',
    duration_in_seconds: '1:48',
    release_date: 2019,
    genre: 'Рок',
  },
  {
    id: 10,
    name: 'Knives n Cherries',
    author: 'minthaze',
    album: 'Captivating',
    duration_in_seconds: '1:48',
    release_date: 2017,
    genre: 'Танцевальная',
  },
  {
    id: 11,
    name: 'Knives n Cherries',
    author: 'minthaze',
    album: 'Captivating',
    duration_in_seconds: '1:48',
    release_date: 2022,
    genre: 'Хип-хоп',
  },
  {
    id: 12,
    name: 'Knives n Cherries',
    author: 'minthaze',
    album: 'Captivating',
    duration_in_seconds: '1:48',
    release_date: 2018,
    genre: 'Из кино',
  },
  {
    id: 13,
    name: 'Knives n Cherries',
    author: 'minthaze',
    album: 'Captivating',
    duration_in_seconds: '1:48',
    release_date: 2020,
    genre: 'Нью-эйдж',
  },
  {
    id: 14,
    name: 'How Deep Is Your Love',
    author: 'Calvin Harris, Disciples',
    album: 'How Deep Is Your Love',
    duration_in_seconds: '3:32',
    release_date: 2019,
    genre: 'Техно',
  },
  {
    id: 15,
    name: 'Morena',
    author: 'Tom Boxer',
    album: 'Soundz Made in Romania',
    duration_in_seconds: '3:36',
    release_date: 2023,
    genre: 'Рок',
  },
];
