export const DataArray = [
  {
    id: 0,
    title: 'Guilt',
    trackAuthor: 'Nero',
    trackAlbumLink: 'Welcome Reality',
    trackTimeText: '4:44',
    year: 2023,
    genre: 'Хип-хоп',
  },
  {
    id: 1,
    title: 'Elektro',
    trackAuthor: 'Dynoro, Outwork, Mr. Gee',
    trackAlbumLink: 'Elektro',
    trackTimeText: '2:22',
    year: 2022,
    genre: 'Поп-музыка',
  },
  {
    id: 2,
    title: 'I’m Fire',
    trackAuthor: 'Ali Bakgor',
    trackAlbumLink: 'I’m Fire',
    trackTimeText: '2:22',
    year: 2021,
    genre: 'Техно',
  },
  {
    id: 3,
    title: 'Non Stop',
    trackAuthor: 'Стоункат, Psychopath',
    trackAlbumLink: 'Non Stop',
    trackTimeText: '4:12',
    year: 2020,
    genre: 'Инди',
  },
  {
    id: 4,
    title: 'Run Run',
    trackAuthor: 'Jaded, Will Clarke, AR/CO',
    trackAlbumLink: 'Run Run',
    trackTimeText: '2:54',
    year: 2019,
    genre: 'Рок',
  },
  {
    id: 5,
    title: 'Eyes on Fire',
    trackAuthor: 'Blue Foundation, Zeds Dead',
    trackAlbumLink: 'Eyes on Fire',
    trackTimeText: '5:20',
    year: 2023,
    genre: 'Из кино',
  },
  {
    id: 6,
    title: 'Mucho Bien',
    trackAuthor: 'HYBIT, Mr. Black, Offer Nissim, Hi Profile',
    trackAlbumLink: 'Mucho Bien',
    trackTimeText: '3:41',
    year: 2022,
    genre: 'Нью-эйдж',
  },
  {
    id: 7,
    title: 'Knives n Cherries',
    trackAuthor: 'minthaze',
    trackAlbumLink: 'Captivating',
    trackTimeText: '1:48',
    year: 2021,
    genre: 'Классика',
  },
  {
    id: 8,
    title: 'Knives n Cherries',
    trackAuthor: 'minthaze',
    trackAlbumLink: 'Captivating',
    trackTimeText: '1:48',
    year: 2020,
    genre: 'Поп-музыка',
  },
  {
    id: 9,
    title: 'Knives n Cherries',
    trackAuthor: 'minthaze',
    trackAlbumLink: 'Captivating',
    trackTimeText: '1:48',
    year: 2019,
    genre: 'Рок',
  },
  {
    id: 10,
    title: 'Knives n Cherries',
    trackAuthor: 'minthaze',
    trackAlbumLink: 'Captivating',
    trackTimeText: '1:48',
    year: 2017,
    genre: 'Танцевальная',
  },
  {
    id: 11,
    title: 'Knives n Cherries',
    trackAuthor: 'minthaze',
    trackAlbumLink: 'Captivating',
    trackTimeText: '1:48',
    year: 2022,
    genre: 'Хип-хоп',
  },
  {
    id: 12,
    title: 'Knives n Cherries',
    trackAuthor: 'minthaze',
    trackAlbumLink: 'Captivating',
    trackTimeText: '1:48',
    year: 2018,
    genre: 'Из кино',
  },
  {
    id: 13,
    title: 'Knives n Cherries',
    trackAuthor: 'minthaze',
    trackAlbumLink: 'Captivating',
    trackTimeText: '1:48',
    year: 2020,
    genre: 'Нью-эйдж',
  },
  {
    id: 14,
    title: 'How Deep Is Your Love',
    trackAuthor: 'Calvin Harris, Disciples',
    trackAlbumLink: 'How Deep Is Your Love',
    trackTimeText: '3:32',
    year: 2019,
    genre: 'Техно',
  },
  {
    id: 15,
    title: 'Morena',
    trackAuthor: 'Tom Boxer',
    trackAlbumLink: 'Soundz Made in Romania',
    trackTimeText: '3:36',
    year: 2023,
    genre: 'Рок',
  },
];
